name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SampleProjectDockerAssignment/SampleProjectDockerAssignment.csproj

    - name: Build project
      run: dotnet build SampleProjectDockerAssignment/SampleProjectDockerAssignment.csproj --configuration Release

    - name: Run tests (if applicable)
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/sampleproject:latest ./SampleProjectDockerAssignment

    # - name: Push Docker image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/sampleproject:latest
